In [1]:
import pandas as pd
train = pd.read_csv('twitter_training.csv')


In [2]:
data = train.sample(10000,random_state=42)
train.shape

(74681, 4)

In [3]:
# data Explorations
train['Positive'].value_counts()

Positive
Negative      22542
Positive      20831
Neutral       18318
Irrelevant    12990
Name: count, dtype: int64

In [12]:
data.head()


,Positive,"im getting on borderlands and i will murder you all ,"
34877,Irrelevant,went to go in george's room to find his door w...
21704,Positive,Yo this looks LIT! Team:GO/Overwatch combo
47008,Negative,Pay attention executive administrators. While ...
7969,Irrelevant,Guy looked at me and says my name was put on t...
454,Positive,one


In [5]:
data.isnull().sum()


2401                                                       0
Borderlands                                                0
Positive                                                   0
im getting on borderlands and i will murder you all ,    101
dtype: int64

In [6]:
data.duplicated().sum()


np.int64(56)

In [7]:
# data Cleaning remove duplicate also
data = data.dropna()
data.isnull().sum()


2401                                                     0
Borderlands                                              0
Positive                                                 0
im getting on borderlands and i will murder you all ,    0
dtype: int64

In [8]:
data.drop_duplicates(inplace = True)

In [30]:
data.duplicated().sum()


np.int64(171)

In [10]:
data.head(5)

,2401,Borderlands,Positive,"im getting on borderlands and i will murder you all ,"
34877,6792,Fortnite,Irrelevant,went to go in george's room to find his door w...
21704,4115,CS-GO,Positive,Yo this looks LIT! Team:GO/Overwatch combo
47008,5665,HomeDepot,Negative,Pay attention executive administrators. While ...
7969,9369,Overwatch,Irrelevant,Guy looked at me and says my name was put on t...
454,2476,Borderlands,Positive,one


In [11]:
data.drop(columns = ['2401','Borderlands'],inplace = True)

In [12]:
data.head(5)

,Positive,"im getting on borderlands and i will murder you all ,"
34877,Irrelevant,went to go in george's room to find his door w...
21704,Positive,Yo this looks LIT! Team:GO/Overwatch combo
47008,Negative,Pay attention executive administrators. While ...
7969,Irrelevant,Guy looked at me and says my name was put on t...
454,Positive,one


In [13]:
data.rename(columns = {'Positive':'Sentiment','im getting on borderlands and i will murder you all ,':'Tweets'},inplace = True)

In [14]:
data.head()

,Sentiment,Tweets
34877,Irrelevant,went to go in george's room to find his door w...
21704,Positive,Yo this looks LIT! Team:GO/Overwatch combo
47008,Negative,Pay attention executive administrators. While ...
7969,Irrelevant,Guy looked at me and says my name was put on t...
454,Positive,one


In [15]:
data[(data['Sentiment'] == 'Positive') | (data['Sentiment'] == 'Negative') | (data['Sentiment'] == 'Neutral')]

,Sentiment,Tweets
21704,Positive,Yo this looks LIT! Team:GO/Overwatch combo
47008,Negative,Pay attention executive administrators. While ...
454,Positive,one
58076,Negative,@Rainbow6Game Server are Available in Xbox 🥺
40659,Positive,so Awesome siege attempt... strangest bleeding...
...,...,...
5763,Neutral,@OtakuWeeb11 Thanks for entering Grand Summone...
6213,Positive,Couldn't agree some more. It'S s excellent.
12347,Negative,Soooo no token market update for the rest of t...
2515,Positive,"For anyone jumping into this Beta weekend, I h..."


In [16]:
data.head()


,Sentiment,Tweets
34877,Irrelevant,went to go in george's room to find his door w...
21704,Positive,Yo this looks LIT! Team:GO/Overwatch combo
47008,Negative,Pay attention executive administrators. While ...
7969,Irrelevant,Guy looked at me and says my name was put on t...
454,Positive,one


In [17]:
data['Sentiment'].value_counts()

Sentiment
Negative      2982
Positive      2795
Neutral       2317
Irrelevant    1759
Name: count, dtype: int64

In [18]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
data['Sentiment'] = le.fit_transform(data['Sentiment'])

In [19]:
data.head(5)


,Sentiment,Tweets
34877,0,went to go in george's room to find his door w...
21704,3,Yo this looks LIT! Team:GO/Overwatch combo
47008,1,Pay attention executive administrators. While ...
7969,0,Guy looked at me and says my name was put on t...
454,3,one


In [20]:
#Tokenizer
from tensorflow.keras.preprocessing.text import Tokenizer
tokenizer = Tokenizer()
tokenizer.fit_on_texts(data['Tweets'])
sequences = tokenizer.texts_to_sequences(data['Tweets'])

In [21]:
tokenizer.word_index

{'the': 1,
 'to': 2,
 'i': 3,
 'and': 4,
 'a': 5,
 'of': 6,
 'is': 7,
 'in': 8,
 'for': 9,
 'this': 10,
 'it': 11,
 'you': 12,
 'on': 13,
 'my': 14,
 'that': 15,
 'com': 16,
 'with': 17,
 'game': 18,
 'so': 19,
 'me': 20,
 'have': 21,
 'be': 22,
 'just': 23,
 'not': 24,
 'but': 25,
 'was': 26,
 'all': 27,
 'are': 28,
 'at': 29,
 'like': 30,
 'out': 31,
 'from': 32,
 '2': 33,
 'your': 34,
 'twitter': 35,
 'pic': 36,
 'as': 37,
 'get': 38,
 'now': 39,
 'we': 40,
 'they': 41,
 'if': 42,
 'good': 43,
 'has': 44,
 't': 45,
 'about': 46,
 'do': 47,
 'play': 48,
 'can': 49,
 'one': 50,
 'people': 51,
 'will': 52,
 'when': 53,
 'new': 54,
 'no': 55,
 'really': 56,
 'love': 57,
 'an': 58,
 "i'm": 59,
 'johnson': 60,
 'more': 61,
 'unk': 62,
 'time': 63,
 'up': 64,
 'some': 65,
 'by': 66,
 'what': 67,
 'see': 68,
 'shit': 69,
 '3': 70,
 'been': 71,
 'how': 72,
 'best': 73,
 'why': 74,
 '’': 75,
 'co': 76,
 'still': 77,
 "it's": 78,
 'or': 79,
 'facebook': 80,
 'who': 81,
 'great': 82,
 'https': 

In [22]:
tokenizer.word_counts

OrderedDict([('went', 65),
             ('to', 3916),
             ('go', 299),
             ('in', 2135),
             ("george's", 2),
             ('room', 16),
             ('find', 77),
             ('his', 168),
             ('door', 9),
             ('was', 782),
             ('locked', 7),
             ('climbed', 2),
             ('up', 408),
             ('side', 22),
             ('of', 2654),
             ('house', 30),
             ('look', 129),
             ('through', 88),
             ('window', 3),
             ('expecting', 3),
             ('see', 370),
             ('a', 3301),
             ('regrettable', 2),
             ('girl', 53),
             ('or', 343),
             ('something', 131),
             ('but', 800),
             ('no', 432),
             ('he', 227),
             ('playing', 296),
             ('fortnite', 164),
             ('yo', 48),
             ('this', 1948),
             ('looks', 136),
             ('lit', 15),
             ('team', 15

In [23]:
from keras.utils import pad_sequences
sequences = pad_sequences(sequences, padding='pre')

In [24]:
print(sequences)


[[   0    0    0 ...   26   90  181]
 [   0    0    0 ...   88  149 2180]
 [   0    0    0 ...    6 1717 2182]
 ...
 [   0    0    0 ...  171  179  598]
 [   0    0    0 ...   83 2110 8758]
 [   0    0    0 ... 3521 5244 3186]]


In [25]:
from tensorflow.keras.layers import Embedding,SimpleRNN,Dense
from tensorflow.keras.models import Sequential
X = sequences

In [26]:
X


array([[   0,    0,    0, ...,   26,   90,  181],
       [   0,    0,    0, ...,   88,  149, 2180],
       [   0,    0,    0, ...,    6, 1717, 2182],
       ...,
       [   0,    0,    0, ...,  171,  179,  598],
       [   0,    0,    0, ...,   83, 2110, 8758],
       [   0,    0,    0, ..., 3521, 5244, 3186]],
      shape=(9853, 74), dtype=int32)

In [27]:
y = data['Sentiment'].values

In [28]:
y


array([0, 3, 1, ..., 1, 3, 2], shape=(9853,))

In [29]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 42)

In [32]:
model = Sequential()
model.add(SimpleRNN(32,input_shape=(99,1),return_sequences=False))
model.add(Dense(3,activation='softmax'))


/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/keras/src/layers/rnn/rnn.py:199: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(**kwargs)


In [33]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ simple_rnn (SimpleRNN)          │ (None, 32)             │         1,088 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense (Dense)                   │ (None, 3)              │            99 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 1,187 (4.64 KB)

 Trainable params: 1,187 (4.64 KB)

 Non-trainable params: 0 (0.00 B)

In [32]:
model.compile(optimizer='adam',metrics=['accuracy'],loss='SparseCategoricalCrossentropy')

In [ ]:
model.fit(X_train,y_train,epochs=10,validation_data=(X_test,y_test),batch_size=128)


Epoch 1/10


In [ ]:
vocab_size = len(tokenizer.word_index) + 1
vocab_size

In [ ]:
vocab_size = len(tokenizer.word_index) + 1
vocab_size